=begin
#Ukraine Alert API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0
Contact: support@stfalcon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

module SwaggerClient
  class RegionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Повертає список усіх областей, регіонів та міст
    # @param [Hash] opts the optional parameters
    # @return [RegionsViewModel]
    def api_v3_regions_get(opts = {})
      data, _status_code, _headers = api_v3_regions_get_with_http_info(opts)
      data
    end

    # Повертає список усіх областей, регіонів та міст
    # @param [Hash] opts the optional parameters
    # @return [Array<(RegionsViewModel, Integer, Hash)>] RegionsViewModel data, response status code and response headers
    def api_v3_regions_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RegionsApi.api_v3_regions_get ...'
      end
      # resource path
      local_var_path = '/api/v3/regions'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      return_type = opts[:return_type] || 'RegionsViewModel' 

      auth_names = opts[:auth_names] || ['Token']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type)

      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RegionsApi#api_v3_regions_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
