=begin
#Ukraine Alert API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0
Contact: support@stfalcon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AlertsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AlertsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AlertsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AlertsApi' do
    it 'should create an instance of AlertsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AlertsApi)
    end
  end

  # unit tests for api_v3_alerts_get
  # Області, регіони та громади з тривогами
  # @param [Hash] opts the optional parameters
  # @return [Array<AlertRegionModel>]
  describe 'api_v3_alerts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v3_alerts_region_history_get
  # Отримати останніх 25 тривог регіону
  # @param [Hash] opts the optional parameters
  # @option opts [String] :region_id 
  # @return [Array<RegionAlarmsHistory>]
  describe 'api_v3_alerts_region_history_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v3_alerts_region_id_get
  # Статус області/регіону/громади
  # @param region_id ID області/регіону/громади
  # @param [Hash] opts the optional parameters
  # @return [Array<AlertRegionModel>]
  describe 'api_v3_alerts_region_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v3_alerts_status_get
  # Перевірка номеру останньої дії. Використовувати для перевірки необхідності оновлювати дані
  # @param [Hash] opts the optional parameters
  # @return [AlertModification]
  describe 'api_v3_alerts_status_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
