=begin
#Ukraine Alert API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0
Contact: support@stfalcon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RegionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RegionsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RegionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RegionsApi' do
    it 'should create an instance of RegionsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RegionsApi)
    end
  end

  # unit tests for api_v3_regions_get
  # Повертає список усіх областей, регіонів та міст
  # @param [Hash] opts the optional parameters
  # @return [RegionsViewModel]
  describe 'api_v3_regions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
