=begin
#Ukraine Alert API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0
Contact: support@stfalcon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::WebHookApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebHookApi' do
  before do
    # run before each test
    @instance = SwaggerClient::WebHookApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebHookApi' do
    it 'should create an instance of WebHookApi' do
      expect(@instance).to be_instance_of(SwaggerClient::WebHookApi)
    end
  end

  # unit tests for api_v3_webhook_delete
  # Відписка на WebHook про нові сирени та їх відбій
  # @param [Hash] opts the optional parameters
  # @option opts [WebHookModel] :body 
  # @return [nil]
  describe 'api_v3_webhook_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v3_webhook_patch
  # Оновлення WebHook посилання про нові сирени та їх відбій
  # @param [Hash] opts the optional parameters
  # @option opts [WebHookModel] :body 
  # @return [nil]
  describe 'api_v3_webhook_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v3_webhook_post
  # Підписка на WebHook про нові сирени та їх відбій. У вебхукі відпрявляється подія тривоги/відбою (приклад в відповіді \&quot;200\&quot;)
  # @param [Hash] opts the optional parameters
  # @option opts [WebHookModel] :body 
  # @return [AlertRegionModel]
  describe 'api_v3_webhook_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
