=begin
#Ukraine Alert API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0
Contact: support@stfalcon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'date'

module SwaggerClient
  class AlertType
    UNKNOWN = 'UNKNOWN'.freeze
    AIR = 'AIR'.freeze
    ARTILLERY = 'ARTILLERY'.freeze
    URBAN_FIGHTS = 'URBAN_FIGHTS'.freeze
    CHEMICAL = 'CHEMICAL'.freeze
    NUCLEAR = 'NUCLEAR'.freeze
    INFO = 'INFO'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = AlertType.constants.select { |c| AlertType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #AlertType" if constantValues.empty?
      value
    end
  end
end
