=begin
#Ukraine Alert API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0
Contact: support@stfalcon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'date'

module SwaggerClient
  class V2RegionType
    STATE = 'State'.freeze
    DISTRICT = 'District'.freeze
    COMMUNITY = 'Community'.freeze
    NULL = 'Null'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = V2RegionType.constants.select { |c| V2RegionType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #V2RegionType" if constantValues.empty?
      value
    end
  end
end
